[package]
kit_sdk_version = "110.*"
version = "3.0.3"
authors = ["Pierre-Olivier Trottier <ptrottier@nvidia.com>"]
title = "NVIDIA RTX Remix ComfyUI Core"
description = "ComfyUI Core implementation for NVIDIA RTX Remix AI Tools"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["comfyui", "core", "ai"]
icon = "data/icon.png"
category = "internal"
preview_image = "data/preview.png"
repository = "https://gitlab-master.nvidia.com/lightspeedrtx/lightspeed-kit/"

[dependencies]
"lightspeed.common" = {}
"lightspeed.events_manager" = {}
"lightspeed.trex.asset_pipeline.core" = {}
"lightspeed.trex.texture_replacements.core.shared" = {}
"lightspeed.trex.utils.common" = {}
"omni.client" = {}
"omni.flux.asset_importer.core" = {}
"omni.flux.factory.base" = {}
"omni.flux.job_queue.core" = {}
"omni.flux.pip_archive" = {}
"omni.flux.utils.common" = {}
"omni.usd" = {}

[settings.persistent.exts."lightspeed.trex.comfyui.core"]
protocol = "http"
host = "127.0.0.1"
port = 8188

[[python.module]]
name = "lightspeed.trex.comfyui.core"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]

[[test]]
name = "startup"
dependencies = [
    "lightspeed.trex.tests.dependencies",
]
