[package]
version = "1.0.0"
authors = ["Pierre-Olivier Trottier <ptrottier@nvidia.com>"]
title = "Remix Stage Manager ComfyUI Listener Plugin"
description = "ComfyUI state change listener plugin for the Remix stage manager"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["remix", "stage", "manager", "plugin", "listener", "comfyui"]
icon = "data/images/icon.png"
category = "internal"
preview_image = "data/images/preview.png"

[dependencies]
"lightspeed.trex.ai_tools.widget" = {}
"omni.flux.pip_archive" = {}  # For pydantic
"omni.flux.stage_manager.factory" = {}
"omni.flux.utils.common" = {}

[[python.module]]
name = "lightspeed.trex.stage_manager.plugin.listener.comfyui"

[[test]]
dependencies = [
    "lightspeed.trex.tests.dependencies",
]

stdoutFailPatterns.exclude = [
    "*[omni.kit.registry.nucleus.utils.common] Skipping deletion of:*",
]
